# Site settings
baseURL = "/"
languageCode = "en-us"
title = "Andrew Abrahamian"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Andrew Abrahamian"
  description = "Portfolio/CV for Andrew Abrahamian"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "public"]

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Andrew Abrahamian"
    subtitle = "Strategy, Analytics, & Data Science"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    #[[params.navigation.links]]
    #  name = "About Me"
    #  url = "about"

    [[params.navigation.links]]
      name = "Blog"
      url = "blogs"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    #[[params.navigation.button1]]
    #  name = "Get Started"
    #  url = "blogs"

    # Button Style 2
    #[[params.navigation.button2]]
    #  name = "Log In"
    #  url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Andrew Abrahamian"
    subtitle = "Portfolio of Strategy & Data Science Projects"
    #buttonText = "Resume"
    #url = "https://github.com/andrewabrahamian/personal/blob/main/Andrew%20Abrahamian%20-%20Resume%20(24-10-17).pdf"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    [[params.tiles.showcase]]
      title = "Predicting Flight Delays"
      subtitle = "Predicting delayed flights in 5Y airline and weather dataset"
      url = "https://andrewabrahamian.github.io/predicting_flight_delays/team_3-3_phase_3_report_w261_final_project.html"
      image = "projects/flight_delay_prediction.png"
    
    [[params.tiles.showcase]]
      title = "Forecasting Wine Prices"
      subtitle = "Hypothesis Testing and EDA of Wine Ratings dataset"
      url = "projects/wine_model_building"
      image = "projects/wine_model_building.png"

    [[params.tiles.showcase]]
      title = "Evaluation of Price Determinants of California Wine"
      subtitle = "Predicing Prices of California Wine"
      url = "projects/wine_model_final"
      image = "projects/wine_model_final.png"

    [[params.tiles.showcase]]
      title = "ECTQA: Expanding Earnings Call Transcript Summarization"
      subtitle = "A novel approach to summarizing earnings call transcripts with LLMs"
      url = "https://github.com/andrewabrahamian/ectqa/blob/main/ECTQA_w266_summer_2023_Abrahamian_Azinge.pdf"
      image = "projects/ectqa.png"

    #[[params.tiles.showcase]]
    #  title = "Lesser Known Tidyverse Functions"
    #  subtitle = "Parsing a twitter thread about tidyverse functions"
    #  url = "projects/tidyverse_functions"
    #  image = "projects/top_functions.jpg"

    
    #[[params.tiles.showcase]]
    #  title = "Chopped Judges"
    #  subtitle = "Are judges associated with overall episode rating?"
    #  image = "projects/chopped.png"
    #  url = "projects/chopped"

    
    #[[params.tiles.showcase]]
    #  title = "Avatar Sentiment Journeys"
    #  subtitle = "Understanding each character's journey through sentiment analysis"
    #  image = "projects/zuko.png"
    #  url = "projects/avatar"

    #[[params.tiles.showcase]]
    #  title = "Shiny App: Palmer Penguin Party"
    #  subtitle = "Using decision trees to build a species predictor for the Palmer Penguin Dataset"
    #  image = "projects/penguin_party.png"
    #  url = "https://tladeras.shinyapps.io/penguin_party/"
    
    
    #[[params.tiles.showcase]]
    #  title = "Project: Understanding Coffee Scores"
    #  subtitle = "Does processing method influence overall score?"
    #  image = "projects/coffee.png"
    #  url = "projects/coffee"
    
    #[[params.tiles.showcase]]
    #  title = "Project: Choropleth of Ready for R Class"
    #  subtitle = "Where are the Ready for R Students From?"
    #  image = "projects/choropleth.png"
    #  url = "projects/choropleth"

    #[[params.tiles.showcase]]
    #  title = "Project: Animal Crossing Tidy Tuesday"
    #  subtitle = "What personality/animal combos are unique?"
    #  image = "projects/ac.png"
    #  url = "projects/animal_crossing"

    #[[params.tiles.showcase]]
    #  title = "Course: Ready for R"
    #  subtitle = "A gentle introduction to the R and the tidyverse"
    #  image = "projects/ready4r.png"
    #  url = "https://ready4r.netlify.app"

    #[[params.tiles.showcase]]
    #  title = "Course: Stats for Neuroscientists"
    #  subtitle = "A Course on Statistical Image Processing for Neuroscientists new to computing"
    #  image = "projects/stats4neuro.png"
    #  url = "https://stats4neuro.netlify.app"
      
    #[[params.tiles.showcase]]
    #  title = "Course: R-Bootcamp"
    #  subtitle = "An interactive introduction to the tidyverse"
    #  image = "projects/r-bootcamp.jpg"
    #  url = "https://r-bootcamp.netlify.app"

    #[[params.tiles.showcase]]
    #  title = "Workshop: A gRadual Introduction to Shiny"
    #  subtitle = "A short workshop introducing basic shiny programming concepts"
    #  image = "projects/r-bootcamp.jpg"
    #  url = "https://laderast.github.io/gradual_shiny/"

    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = false
    title = "Massa libero"
    subtitle = """Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. 
    Mauris aliquet magna magna sed nunc rhoncus pharetra. 
    Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor. 
    Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero.
    Mauris aliquet magna magna sed nunc rhoncus amet pharetra et feugiat tempus."""
    buttonText = "Get Started"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "andrew.abrahamian (at) gmail.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(774) 641-4927"

    [[params.contact.address]]
    title = "Location"
    city = "Boston, MA"
    country = "USA"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Andrew Abrahamian"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/andrew-abrahamian"
      label = "LinkedIn"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/andrewabrahamian"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-pdf-o"
      url= "https://github.com/andrewabrahamian/personal/blob/c6197a028c7bdf11c48bec13cc8306a942fa63c6/Andrew%20Abrahamian%20-%20Resume%20(24-10-17).pdf"
      label = "Resume"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
